<?php

namespace Application\Sonata\MediaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostAssetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryRepository extends EntityRepository
{
    public function getAllSubGalleriesMedia( Gallery $mainCategory, $returnParent = false) {
        $em = $this->getEntityManager();
        $mainId = $mainCategory->getId();
        $galleries = $this->getSubGalleries($mainId);
        $media = [];
        $galleryNames = [];

        $mediaQuery = $em->createQuery('SELECT ghm FROM ApplicationSonataMediaBundle:GalleryHasMedia ghm WHERE ghm.gallery IN(:subgalleries) AND ghm.enabled=1')
                         ->setParameter('subgalleries', $galleries);

// TODO: add posibility to return media from parent gallery with children

        foreach ($mediaQuery->iterate() as $key => $value) {
            $media[] = array('media'=>$value[0]->getMedia(),
                             'name'=>$value[0]->getGallery()->getName(),
                            );
            if(!in_array($value[0]->getGallery()->getName(), $galleryNames)) {
                array_push($galleryNames,$value[0]->getGallery()->getName());
            }
        }

        return array('media'=>$media,'nameMedia'=>$galleryNames);
    }

    public function getSubGalleries($mainGalleryId)
    {
        $em = $this->getEntityManager();
        $subGalleryQuery = $em->createQuery('SELECT g.id FROM DJBlogBundle:SubGallery s JOIN s.childrenGallery g WHERE s.parentGallery=:parent')
                            ->setParameter('parent',$mainGalleryId);

        return $subGalleryQuery->getArrayResult();
    }

    public function getAllMainGalleries()
    {
        $em = $this->getEntityManager();
        $galleriesQuery = $em->createQuery('SELECT g FROM ApplicationSonataMediaBundle:Gallery g WHERE g.parent IS NULL AND g.enabled=1');

        return $galleriesQuery->getArrayResult();
    }
}