dj_blog:
    resource: "@DJBlogBundle/Controller/"
    type:     annotation
    prefix:   /

dj_main:
    resource: "@DJMainBundle/Controller/"
    type:     annotation
    prefix:   /
    
dj_admin:
    resource: "@DJAdminBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
