parameters:
    sonata.media.admin.media.class: Application\Sonata\MediaBundle\Admin\ORM\MediaAdmin
    sonata.media.admin.gallery.class: Application\Sonata\MediaBundle\Admin\ORM\GalleryAdmin
    sonata.gallery.repository.class: Application\Sonata\MediaBundle\Entity\GalleryRepository

services:
    application.admin.media:
        class: %sonata.media.admin.media.class%
        arguments:
            - ~
            - Application\Sonata\MediaBundle\Entity\Media
            - ApplicationSonataMediaBundle:MediaAdmin
            - @sonata.media.pool
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Media}

    application.admin.gallery:
        class: %sonata.media.admin.gallery.class%
        arguments:
            - ~
            - Application\Sonata\MediaBundle\Entity\Gallery
            - ApplicationSonataMediaBundle:GalleryAdmin
            - @sonata.media.pool
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Gallery}
