parameters:
#    dj_admin.example.class: DJ\AdminBundle\Example

services:
#    dj_admin.example:
#        class: %dj_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
