parameters:
#    dj_admin.example.class: DJ\AdminBundle\Example

#services:
#    dj_admin.example:
#        class: %dj_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    sonata.admin.post:
        class: DJ\AdminBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "dj.admin.group.content", label: "Post" }
        arguments:
            - ~
            - DJ\BlogBundle\Entity\Post
            - 'DJAdminBundle:PostCRUD' # define the new controller via the third argument
        calls:
            - [ setTranslationDomain, [DJ\AdminBundle]]