DJ\BlogBundle\Entity\Category:
    constraints:
        - Sonata\AdminBundle\Validator\Constraints\InlineConstraint:
            service: sonata.admin.category
            method: validationCategory

DJ\BlogBundle\Entity\Post:
    constraints:
        - Sonata\AdminBundle\Validator\Constraints\InlineConstraint:
            service: sonata.admin.post
            method: validationCategory

DJ\BlogBundle\Entity\Asset:
    constraints:
        - Sonata\AdminBundle\Validator\Constraints\InlineConstraint:
            service: dj_admin.admin.asset
            method: validationCategory
